// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

// Import schema type
import { SchemaType } from "@latticexyz/schema-type/src/solidity/SchemaType.sol";

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout, FieldLayoutLib } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema, SchemaLib } from "@latticexyz/store/src/Schema.sol";
import { PackedCounter, PackedCounterLib } from "@latticexyz/store/src/PackedCounter.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { RESOURCE_TABLE, RESOURCE_OFFCHAIN_TABLE } from "@latticexyz/store/src/storeResourceTypes.sol";

// Import user types
import { MainObject } from "./../common.sol";

ResourceId constant _tableId = ResourceId.wrap(
  bytes32(abi.encodePacked(RESOURCE_TABLE, bytes14(""), bytes16("BestScore")))
);
ResourceId constant BestScoreTableId = _tableId;

FieldLayout constant _fieldLayout = FieldLayout.wrap(
  0x0005020104010000000000000000000000000000000000000000000000000000
);

struct BestScoreData {
  uint32 score;
  MainObject mainObjectKind;
  string gameName;
}

library BestScore {
  /**
   * @notice Get the table values' field layout.
   * @return _fieldLayout The field layout for the table.
   */
  function getFieldLayout() internal pure returns (FieldLayout) {
    return _fieldLayout;
  }

  /**
   * @notice Get the table's key schema.
   * @return _keySchema The key schema for the table.
   */
  function getKeySchema() internal pure returns (Schema) {
    SchemaType[] memory _keySchema = new SchemaType[](1);
    _keySchema[0] = SchemaType.BYTES32;

    return SchemaLib.encode(_keySchema);
  }

  /**
   * @notice Get the table's value schema.
   * @return _valueSchema The value schema for the table.
   */
  function getValueSchema() internal pure returns (Schema) {
    SchemaType[] memory _valueSchema = new SchemaType[](3);
    _valueSchema[0] = SchemaType.UINT32;
    _valueSchema[1] = SchemaType.UINT8;
    _valueSchema[2] = SchemaType.STRING;

    return SchemaLib.encode(_valueSchema);
  }

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "player";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "score";
    fieldNames[1] = "mainObjectKind";
    fieldNames[2] = "gameName";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config (using the specified store).
   */
  function register(IStore _store) internal {
    _store.registerTable(_tableId, _fieldLayout, getKeySchema(), getValueSchema(), getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get score.
   */
  function getScore(bytes32 player) internal view returns (uint32 score) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get score.
   */
  function _getScore(bytes32 player) internal view returns (uint32 score) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get score (using the specified store).
   */
  function getScore(IStore _store, bytes32 player) internal view returns (uint32 score) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set score.
   */
  function setScore(bytes32 player, uint32 score) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((score)), _fieldLayout);
  }

  /**
   * @notice Set score.
   */
  function _setScore(bytes32 player, uint32 score) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((score)), _fieldLayout);
  }

  /**
   * @notice Set score (using the specified store).
   */
  function setScore(IStore _store, bytes32 player, uint32 score) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    _store.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((score)), _fieldLayout);
  }

  /**
   * @notice Get mainObjectKind.
   */
  function getMainObjectKind(bytes32 player) internal view returns (MainObject mainObjectKind) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return MainObject(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get mainObjectKind.
   */
  function _getMainObjectKind(bytes32 player) internal view returns (MainObject mainObjectKind) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return MainObject(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get mainObjectKind (using the specified store).
   */
  function getMainObjectKind(IStore _store, bytes32 player) internal view returns (MainObject mainObjectKind) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes32 _blob = _store.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return MainObject(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set mainObjectKind.
   */
  function setMainObjectKind(bytes32 player, MainObject mainObjectKind) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(mainObjectKind)), _fieldLayout);
  }

  /**
   * @notice Set mainObjectKind.
   */
  function _setMainObjectKind(bytes32 player, MainObject mainObjectKind) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(mainObjectKind)), _fieldLayout);
  }

  /**
   * @notice Set mainObjectKind (using the specified store).
   */
  function setMainObjectKind(IStore _store, bytes32 player, MainObject mainObjectKind) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    _store.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked(uint8(mainObjectKind)), _fieldLayout);
  }

  /**
   * @notice Get gameName.
   */
  function getGameName(bytes32 player) internal view returns (string memory gameName) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get gameName.
   */
  function _getGameName(bytes32 player) internal view returns (string memory gameName) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get gameName (using the specified store).
   */
  function getGameName(IStore _store, bytes32 player) internal view returns (string memory gameName) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    bytes memory _blob = _store.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set gameName.
   */
  function setGameName(bytes32 player, string memory gameName) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((gameName)));
  }

  /**
   * @notice Set gameName.
   */
  function _setGameName(bytes32 player, string memory gameName) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((gameName)));
  }

  /**
   * @notice Set gameName (using the specified store).
   */
  function setGameName(IStore _store, bytes32 player, string memory gameName) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    _store.setDynamicField(_tableId, _keyTuple, 0, bytes((gameName)));
  }

  /**
   * @notice Get the length of gameName.
   */
  function lengthGameName(bytes32 player) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of gameName.
   */
  function _lengthGameName(bytes32 player) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of gameName (using the specified store).
   */
  function lengthGameName(IStore _store, bytes32 player) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    uint256 _byteLength = _store.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of gameName.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemGameName(bytes32 player, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of gameName.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemGameName(bytes32 player, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of gameName (using the specified store).
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemGameName(IStore _store, bytes32 player, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    unchecked {
      bytes memory _blob = _store.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to gameName.
   */
  function pushGameName(bytes32 player, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to gameName.
   */
  function _pushGameName(bytes32 player, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to gameName (using the specified store).
   */
  function pushGameName(IStore _store, bytes32 player, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    _store.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from gameName.
   */
  function popGameName(bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from gameName.
   */
  function _popGameName(bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from gameName (using the specified store).
   */
  function popGameName(IStore _store, bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    _store.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of gameName at `_index`.
   */
  function updateGameName(bytes32 player, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of gameName at `_index`.
   */
  function _updateGameName(bytes32 player, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of gameName (using the specified store) at `_index`.
   */
  function updateGameName(IStore _store, bytes32 player, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      _store.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 player) internal view returns (BestScoreData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 player) internal view returns (BestScoreData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data (using the specified store).
   */
  function get(IStore _store, bytes32 player) internal view returns (BestScoreData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    (bytes memory _staticData, PackedCounter _encodedLengths, bytes memory _dynamicData) = _store.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 player, uint32 score, MainObject mainObjectKind, string memory gameName) internal {
    bytes memory _staticData = encodeStatic(score, mainObjectKind);

    PackedCounter _encodedLengths = encodeLengths(gameName);
    bytes memory _dynamicData = encodeDynamic(gameName);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 player, uint32 score, MainObject mainObjectKind, string memory gameName) internal {
    bytes memory _staticData = encodeStatic(score, mainObjectKind);

    PackedCounter _encodedLengths = encodeLengths(gameName);
    bytes memory _dynamicData = encodeDynamic(gameName);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using individual values (using the specified store).
   */
  function set(
    IStore _store,
    bytes32 player,
    uint32 score,
    MainObject mainObjectKind,
    string memory gameName
  ) internal {
    bytes memory _staticData = encodeStatic(score, mainObjectKind);

    PackedCounter _encodedLengths = encodeLengths(gameName);
    bytes memory _dynamicData = encodeDynamic(gameName);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 player, BestScoreData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.score, _table.mainObjectKind);

    PackedCounter _encodedLengths = encodeLengths(_table.gameName);
    bytes memory _dynamicData = encodeDynamic(_table.gameName);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 player, BestScoreData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.score, _table.mainObjectKind);

    PackedCounter _encodedLengths = encodeLengths(_table.gameName);
    bytes memory _dynamicData = encodeDynamic(_table.gameName);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct (using the specified store).
   */
  function set(IStore _store, bytes32 player, BestScoreData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.score, _table.mainObjectKind);

    PackedCounter _encodedLengths = encodeLengths(_table.gameName);
    bytes memory _dynamicData = encodeDynamic(_table.gameName);

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    _store.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint32 score, MainObject mainObjectKind) {
    score = (uint32(Bytes.slice4(_blob, 0)));

    mainObjectKind = MainObject(uint8(Bytes.slice1(_blob, 4)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    PackedCounter _encodedLengths,
    bytes memory _blob
  ) internal pure returns (string memory gameName) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    gameName = (string(SliceLib.getSubslice(_blob, _start, _end).toBytes()));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    PackedCounter _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (BestScoreData memory _table) {
    (_table.score, _table.mainObjectKind) = decodeStatic(_staticData);

    (_table.gameName) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Delete all data for given keys (using the specified store).
   */
  function deleteRecord(IStore _store, bytes32 player) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    _store.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint32 score, MainObject mainObjectKind) internal pure returns (bytes memory) {
    return abi.encodePacked(score, mainObjectKind);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory gameName) internal pure returns (PackedCounter _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = PackedCounterLib.pack(bytes(gameName).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory gameName) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((gameName)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dyanmic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 score,
    MainObject mainObjectKind,
    string memory gameName
  ) internal pure returns (bytes memory, PackedCounter, bytes memory) {
    bytes memory _staticData = encodeStatic(score, mainObjectKind);

    PackedCounter _encodedLengths = encodeLengths(gameName);
    bytes memory _dynamicData = encodeDynamic(gameName);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 player) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = player;

    return _keyTuple;
  }
}
