// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum VictoryCondition {
  LastManStanding,
  MostPoints,
  MostTeritory
}

enum TerrainKind {
  Square,
  Flat
}

enum MainObject {
  Cell,
  Food,
  Virus,
  Trail
}

enum SubObject {
  SplitCell,
  Teritory
}

enum Attribution {
  Movable,
  Immovable
}

enum CollisionDetection {
  NoCollision,
  PartialOverlap,
  FullOverlap,
  Crossing,
  Touching
}

enum CollisionEffect {
  GainLives,
  LoseLives,
  GainPoints,
  LosePoints,
  SpeedUp,
  SpeedDown,
  Absorb,
  Stun
}

enum MoveEffect {
  Movable,
  Stunned,
  Expanding,
  Splitting
}

enum Progress {
  Waiting,
  Started,
  Dead,
  Finished
}
