// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Name, NameTableId } from "./tables/Name.sol";
import { Score, ScoreTableId } from "./tables/Score.sol";
import { Character, CharacterTableId } from "./tables/Character.sol";
import { IsPlay, IsPlayTableId } from "./tables/IsPlay.sol";
import { PlayerMainEntity, PlayerMainEntityTableId } from "./tables/PlayerMainEntity.sol";
import { PlayerSubEntity, PlayerSubEntityTableId } from "./tables/PlayerSubEntity.sol";
import { BestScore, BestScoreData, BestScoreTableId } from "./tables/BestScore.sol";
import { CurrentPlayers, CurrentPlayersTableId } from "./tables/CurrentPlayers.sol";
import { MaxPlayers, MaxPlayersTableId } from "./tables/MaxPlayers.sol";
import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { Duration, DurationTableId } from "./tables/Duration.sol";
import { Rule, RuleTableId } from "./tables/Rule.sol";
import { Terrain, TerrainTableId } from "./tables/Terrain.sol";
import { MainObjectKind, MainObjectKindTableId } from "./tables/MainObjectKind.sol";
import { ObjectAttribution, ObjectAttributionTableId } from "./tables/ObjectAttribution.sol";
import { ObjectCollision, ObjectCollisionTableId } from "./tables/ObjectCollision.sol";
import { ObjectCollisionEffect, ObjectCollisionEffectTableId } from "./tables/ObjectCollisionEffect.sol";
import { ObjectEffectTime, ObjectEffectTimeTableId } from "./tables/ObjectEffectTime.sol";
import { ObjectQuantity, ObjectQuantityTableId } from "./tables/ObjectQuantity.sol";
import { ObjectCount, ObjectCountTableId } from "./tables/ObjectCount.sol";
import { ObjectCoordinate, ObjectCoordinateData, ObjectCoordinateTableId } from "./tables/ObjectCoordinate.sol";
import { ObjectDrawing, ObjectDrawingData, ObjectDrawingTableId } from "./tables/ObjectDrawing.sol";
import { GameProgress, GameProgressTableId } from "./tables/GameProgress.sol";
import { ObjectMoveEffect, ObjectMoveEffectTableId } from "./tables/ObjectMoveEffect.sol";
import { ObjectSize, ObjectSizeTableId } from "./tables/ObjectSize.sol";
import { ObjectLives, ObjectLivesTableId } from "./tables/ObjectLives.sol";
import { ObjectSpeed, ObjectSpeedTableId } from "./tables/ObjectSpeed.sol";
