// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { TerrainKind, VictoryCondition } from "./../common.sol";

/**
 * @title IGameEntitySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameEntitySystem {
  function CreateGameEntity(
    uint32 maxPlayers,
    string memory gameName,
    uint32 duration,
    TerrainKind terrainKind,
    VictoryCondition victoryCondition
  ) external;
}
