// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { MainObject, Attribution, CollisionDetection, CollisionEffect } from "./../common.sol";

/**
 * @title IObjectEntitySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IObjectEntitySystem {
  function CreateObjectEntity(
    string memory gameName,
    uint32 effectTime,
    uint32 quantity,
    MainObject mainObject,
    Attribution attribution,
    CollisionDetection collisionDetection,
    CollisionEffect collisionEffect
  ) external;
}
