// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPlayerSettingSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlayerSettingSystem {
  function CreatePlayer(string memory name, string memory character) external;

  function ChangeName(string memory name) external;

  function ChangeCharacter(string memory character) external;
}
