// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IPlaySystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPlaySystem {
  function Join(string memory gameName, bytes32 objectEntity, uint32 x, uint32 y) external;

  function Dead() external;

  function End(string memory gameName) external;

  function Move(string memory gameName, uint32 x, uint32 y) external;

  function Draw(string memory gameName, uint32 x, uint32 y) external;
}
