// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IGameEntitySystem } from "./IGameEntitySystem.sol";
import { IObjectEntitySystem } from "./IObjectEntitySystem.sol";
import { IPlayerSettingSystem } from "./IPlayerSettingSystem.sol";
import { IPlaySystem } from "./IPlaySystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is IBaseWorld, IGameEntitySystem, IObjectEntitySystem, IPlayerSettingSystem, IPlaySystem {

}
